name: chatApp
description: "A bluetooth app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  intl:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  permission_handler: ^10.2.0
  animated_bottom_navigation_bar: ^1.3.3
  bluetooth_classic: ^0.0.2
  all_bluetooth: ^0.1.0
  flutter_ringtone_player: ^4.0.0+3
  flutter_blue_plus: ^1.34.5
#  nearby_service: ^0.1.2
#  device_info_plus: ^11.1.1
#  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
